### ISSUE TITLE
Find a method of alerting new publications about ion channels of interest

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#10]
In order to being aware of new publications about patch clamp experiments, new biological studies related to ion channels in C. elegans, etc in an automatic way, we need a procedure (something like a [RSS feed](http://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&term=%28%28channel%5BTitle%5D%29+AND+%28elegans%5BTitle%5D+OR+nematod%5BTitle%5D%29%29) reader with text mining abilities!). then we can augment it by some alerting (mailing) system.

**Comment by slarson** [comment]
@VahidGh Have you looked at Textpresso?  I wonder if there is something in there we could reuse?

**Comment by VahidGh** [comment]
@slarson, that's cool, especially has a separate section for C. elegans.

**Comment by gsarma** [comment]
Google notifications will probably give us decent mileage.  Would be a nice simple project also for a newcomer to write a script to periodically search the Textpresso _C. elegans_ section.
