### ISSUE TITLE
Collect protein sequence data for ion channels in C. elegans

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#112]
For estimating kinetics, we need to collect protein/structural data about ion channels in C. elegans.

This could be done by some script which is able to: 

1) Retrieve the protein entry in WormBase (e.g. [EGL-19, isoform a](http://www.wormbase.org/species/c_elegans/protein/WP:CE28820#061--10)) for the ion channel of interest from the [spreadsheet](https://docs.google.com/spreadsheets/d/1Oct5cXqSUhLLcPe18Ue11VoLZbeyxO8OdSmPnKxy3ac/edit#gid=1) which is now available via [this DB](https://github.com/VahidGh/ChannelWorm/blob/master/channelworm/db.sqlite3).

2) Get the provided external link by WormBase for UniProt (e.g. [G5EG02](http://www.ebi.uniprot.org/entry/G5EG02)).

3) Retrieve the protein sequence in FASTA format (e.g. [G5EG02.fasta](http://www.uniprot.org/uniprot/G5EG02.fasta)).

**Comment by travs** [comment]
@a-palyanov Hey Andrey, this breaks down some of the data searching you, Vahid and I talked about a little while ago. Is this issue something you'd want to take on?

Here's the link to [your spreadsheet](https://docs.google.com/spreadsheets/d/1Dc0FlreJ06cpZo_rFLTnsp4iYPUzPa0a85uMwCGjxoY/edit#gid=0) that is a good start on collecting some of this data.

Pasting this in some other issues to link you into them, as you mentioned you were interested in data collection.

**Comment by VahidGh** [comment]
Because some of the WormBase REST APIs are broken, such as those for [proteins](http://api.wormbase.org/rest/field/protein/WP:CE33017/corresponding_gene) according to [this doc](https://www.wormbase.org/about/userguide/for_developers/API-REST/Protein#0--10), going to use alternative tools for retrieving required info (such as mining WB web pages, or `BioPython` package + `Entrez` search utilities)

In WormBase, some query like this:
`https://www.wormbase.org/search/autocomplete/protein?term=slo-2`

Returns information about the proteins of the ion channel of interest, in JSON format.
Then the protein id, and it's WB url (e.g. `/species/c_elegans/protein/WP:CE09233`), could be retrieved (in the ion channel spreadsheet we have this link only for the first protein.)

By following each link, it is possible to download the protein sequence and access to related data.

**Comment by VahidGh** [comment]
Done, using [this script](https://github.com/openworm/ChannelWorm/blob/dev/channelworm/predictor/protein_data.py).
Also some other channels get updated.
