### ISSUE TITLE
Collect a dataset of electrophysiology data for ion channels in any type

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#113]
For kinetics estimation from structural properties for ion channels in C. elegans, we need to collect a dataset of available electrophysiology data. 
For each ion channel, data should at least contain: activation time constant, V_half, and activation slope.

Available datasets are: 

1) [Channelpedia](http://channelpedia.epfl.ch/), is a DB of ion channels in mammalians. 
For this case, data could be retrieved using [these scripts](https://github.com/openworm/BlueBrainProjectShowcase/tree/master/Channelpedia), and values taken from available models.

2) [VKCDB](http://vkcdb.biology.ualberta.ca/), is a comprehensive sequence database of voltage-gated potassium channels from Eukaryotes, Bacteria and Archaea. 
[A sample](http://vkcdb.biology.ualberta.ca/view_record.php?vkcid=VKC0) of available electrophysiology data. 
Entire DB is available through [this link](http://vkcdb.biology.ualberta.ca/databases.php).

**Comment by travs** [comment]
@a-palyanov Hey Andrey, this breaks down some of the data searching you, Vahid and I talked about a little while ago. Is this issue something you'd want to take on?

Here's the link to [your spreadsheet](https://docs.google.com/spreadsheets/d/1Dc0FlreJ06cpZo_rFLTnsp4iYPUzPa0a85uMwCGjxoY/edit#gid=0) that is a good start on collecting some of this data.

Pasting this in some other issues to link you into them, as you mentioned you were interested in data collection.

**Comment by rgerkin** [comment]
@VahidGh Doesn't Channelpedia have NeuroML files for each channel?  They are supposed to...

**Comment by VahidGh** [comment]
@rgerkin, yep, and I've mentioned related scripts to retrieve data from. But unfortunately is not very well-defined. all parameters are within "expression" variables, and not in their right place, so needs some regular expression to find out desired values.

**Comment by rgerkin** [comment]
@VahidGh Sharon Crook tells me that @pgleeson has some corrected files, which may be available from him or from OpenSourceBrain.

**Comment by VahidGh** [comment]
@rgerkin, good news, thanks. 
@pgleeson, would be great if we could have those files, or any related dataset.

**Comment by pgleeson** [comment]
I've tidied up the https://github.com/OpenSourceBrain/BlueBrainProjectShowcase project a bit to use pyNeuroML & added some more of the channels [converted to NeuroML2](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/tree/master/Channelpedia/test). **Note: these haven't been verified against the behaviour shown on Channelpedia for these channel models**

**Comment by VahidGh** [comment]
@pgleeson, Thanks, going to see if I can extract meaningful values (such as tau, V_half, etc) from these models.

**Comment by pgleeson** [comment]
Ok @VahidGh, but please consider the files in the [test folder](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/tree/master/Channelpedia/test) as unverified.

**Comment by VahidGh** [comment]
@pgleeson, OK, thanks. Do you have any suggestion for any verification step I can take?

I did some basic verification tests today. For example, this is the result for the kinetics of the Kfast channel of Rat from [a Channelpedia model](http://channelpedia.epfl.ch/ionchannels/188) which is similar to Kfast (SHL-1) channel being used in the Boyle&Cohen model for C. elegans:

![image](https://cloud.githubusercontent.com/assets/6655104/9177217/3894f68e-3fa5-11e5-8875-0892f2e0c83f.png)

And this is the result, generated by `pynml-channelanalysis` from [this file](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/Channelpedia/test/Channelpedia_Kfast_32.channel.nml):

![image](https://cloud.githubusercontent.com/assets/6655104/9177441/721a9412-3fa6-11e5-9e00-99ac27fe1385.png)
![image](https://cloud.githubusercontent.com/assets/6655104/9177450/88118096-3fa6-11e5-9e0c-a009f4ba48e6.png)

They look the same (considering scales).
What else can I do?

**Comment by rgerkin** [comment]
@VahidGh The channelpedia figures do not exist in a digitized form, do they?  If not, perhaps just show side-by-side comparisons (m vs m, h vs h) in notebook subplots (loading the channelpedia figure into one subplot, and plotting the channel analysis in the other), and then give each comparison a qualitative score from 1-5.  The total verification level can be an average of the scores for each channel gate.  Or something like that.

**Comment by VahidGh** [comment]
@rgerkin, Right, plots from Channelpedia do not exist in a digitized form. So, I also need to separate final results (m and h) of the channel analysis script, due to the scaling issues.

**Comment by VahidGh** [comment]
@rgerkin, @pgleeson, I could do some good predictions using data from VKCDB for parameters like V_half activation and inactivation, but variables like tau were rare in this dataset. 

I decided to build a unified dataset of ion channel models and electophysiology data by integrating these with models from channelpedia and Neuroml-db, so will merge duplicates and add data like gene/protein for available models (especially in Neuroml-db case).

We have also some models available [here](http://senselab.med.yale.edu/ModelDb/ModelList.cshtml?id=3540), which seems like we have converted models to NeuroMl for most (if not all) of them. And also some model [here](http://www.opensourcebrain.org/status), that should be mined for channel models.

What do you think about the unified ion channel model dataset in NeuroML which also links to related genes,proteins, etc?

Also if you know any similar work on Drosophila, would be great.
