### ISSUE TITLE
Collect protein sequences for ion channels with available electrophysiology data

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#114]
As same as #112, we should collect protein sequences for collected ion channels in other species (related to #113).

**Comment by travs** [comment]
@a-palyanov Hey Andrey, this breaks down some of the data searching you, Vahid and I talked about a little while ago. Is this issue something you'd want to take on?

Here's the link to [your spreadsheet](https://docs.google.com/spreadsheets/d/1Dc0FlreJ06cpZo_rFLTnsp4iYPUzPa0a85uMwCGjxoY/edit#gid=0) that is a good start on collecting some of this data.

Pasting this in some other issues to link you into them, as you mentioned you were interested in data collection.
