### ISSUE TITLE
Specify data points numerically instead of via mouse interface

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#124]
Raised in the google doc discussion:
>Can we specify data points numerically instead of via mouse interface? In the workflow video, data points from -60mV to -20mV were clearly 0, having to center mouse clicks on them simply introduced errors.

@VahidGh

**Comment by VahidGh** [comment]
After selecting the point via digitizer, it is possible to edit the final result, when clicking on `view data`. Although using cwFitter there is no need to have precise values. We find the closest values approximately, using digitized data.

**Comment by travs** [comment]
@VahidGh Ok, since we have this ability I'll close this one now.
