### ISSUE TITLE
Test suite directory structure

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#136]
@gsarma and I have started to define a testing directory structure, but the django app doesn't obey this by default.

To give a sense of how this spreads out our tests, check out this [tree diagram](https://gist.githubusercontent.com/travs/7bc86d775cb0cd072669/raw/3a099de25dc4c7946f7255304c856007e5208622/channelworm_tree.md)

PyTest may have some extension that remedies this, so after #135 we can check that out.

@kevcmk, you have some experience with PyTest; have you come across anything like this in your travels?

**Comment by rgerkin** [comment]
Whatever you pick, I'll probably refine at the level of the SciUnit tests according to a schema I had in mind, something like:  
```
capabilities.py
tests.py
models.py (basically just a wrapper to the actual model files).  
```
with a .scidash file at the root pointing to this directory.

**Comment by kevcmk** [comment]
That shouldn't affect pytest as long as test functions are still prefixed with test_ and root test cases/suites with Test (no underscore)

**Comment by rgerkin** [comment]
@kevcmk For pytest to know what to do with SciUnit tests, I think there would need to be a test_* function wrapping the instantiation and execution of the SciUnit test.  Otherwise it's not going to know what to do.

**Comment by kevcmk** [comment]
@rgerkin If there's a pressing need, we can swap the function and/or file name filters.  But yea, wrapping them in a test_ call is the standard for pytest.

**Comment by travs** [comment]
Closed by 
https://github.com/openworm/ChannelWorm/commit/caaca7368d86b4362a84c3a97e7096b5fbd85eac

**Comment by travs** [comment]
Closed by 
https://github.com/openworm/ChannelWorm/commit/caaca7368d86b4362a84c3a97e7096b5fbd85eac
