### ISSUE TITLE
Store relevant parameters of experiments

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#138]
Some parameters like membrane capacitance, conductance, and reversal potentials are usually available along with the patch clamp experiment in the same paper.
It would be very useful if we could also store such parameters, when reviewing papers.
For this to be done, we need to consider some fields in existing models and forms.

**Comment by VahidGh** [comment]
@travs, As discussed [here](https://github.com/openworm/muscle_model/issues/49), some of these parameters are cell properties (such as membrane capacitance, area, channel densities, etc). For example, experiment x claims the membrane capacitance for cell y is z. Then we can query PyOW to find those values and use for tests, models, etc. This is the same case for cell types, etc that we need when building (testing) a model.

**Comment by travs** [comment]
@VahidGh Ok, how do you think this could be accomplished? Should I build some function for importing this data from PyOpenWorm, or do you think the PyOpenWorm API will be good enough for this as it is?

Also, as for use case, will we be pulling in the data and storing it in CW as well, or will it be pulled dynamically as we are running tests/models/other things?

**Comment by VahidGh** [comment]
I don't know if PyOW have data models for storing properties of cells. We need to have this one at the first place. Then we can use PyOW API within the CW (or any other project) to read such data.

**Comment by travs** [comment]
@VahidGh You're right, that will definitely need to be in place in pyopenworm before this is possible.

**Comment by VahidGh** [comment]
Also, another useful parameter for each cell is the area of the cell. If we had this, we could also calculate the membrane capacitance from this value (by multiplying the area by specific capacitance (0.01 F/m2)). Do we have such data in the PyOW?

**Comment by travs** [comment]
@VahidGh No :( But it is something we can add a field for!

**Comment by pgleeson** [comment]
This seems to be a potential case again of blurring the lines between asking PyOpenWorm for experimental data and model specific data. 

Certainly something like surface area could be stored in PyOpenWorm, if it was made clear that these values were based on the Blender reconstructions, and even total capacitance if there was an experimental figure for this.

However, channel densities and even specific capacitance can be very model specific and there could be very good reasons for using different values in different models based on expected usage of the models.

**Comment by VahidGh** [comment]
@pgleeson, thanks for the clarification. One problem I encountered experimentally was the estimation of some of these parameters during optimization and modeling. I know some of these parameters are not the same under different conditions, but having some estimation, would help better constraining and validating results.

Specifically, membrane capacitance/surface area for each cell, and e_rev, and conductance reported for channels from the same family.
