### ISSUE TITLE
Test validation test template

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#154]
Right now we have a skipped test for the validation template for models with patch clamp data. 

This is just a test that we can run the iPython notebook @rgerkin made, so it shouldn't be too hard to get passing again.

**Comment by travs** [comment]
@rgerkin Trying to run the ipy notebook and getting an [error with neuronunit](https://gist.github.com/anonymous/bcdba104bea7491cd89b). Looks like some assertion in [this method](https://github.com/scidash/neuronunit/blob/4ce87f9a0ff89f628916f5ebac1c3d247ced522f/neuronunit/tests/channel.py#L20-L24) is failing. I'm assuming this means the observation is not valid? It's not clear why this ran before, but does not currently work.

**Comment by rgerkin** [comment]
@travs The data being passed to it used to be a list and is now a tuple.  I was previously only accepting lists and np arrays.  I added tuples so the rgerkin fork should work now but wait until the tests run and I'll give you a pip upgrade path.

**Comment by travs** [comment]
Ok awesome! Thanks for checking this out Rick

**Comment by rgerkin** [comment]
@travs Try upgrading neuronunit via pip and run the notebook again.

**Comment by travs** [comment]
@rgerkin Ok, tl;dr, this is a long comment about my install troubles, since python's packaging/install system is a mess. Does the notebook work for you in the end? If so, could you do a quick `pip list` and see if I'm missing something locally?

[My `pip list`](https://gist.github.com/anonymous/332a298a34a6ef49fe5f)

**begin**
When installing from a `git+https://package`, I could never get the dependencies from `dependency_links` in `package` to work automatically. When I install neuronunit like 
```
pip install -e git+https://github.com/rgerkin/neuronunit.git#egg=neuronunit
```
I have `elephant (0.1.0)` and `neo (0.3.3)`, for some reason, even though the setup.py in neuronunit specifies other versions.

I tried installing the dependencies manually, like in neuronunit's dependency_links, so I did:
```
pip install git+http://github.com/neuralensemble/python-neo.git#egg=neo-0.4.0dev
pip install git+http://github.com/neuralensemble/elephant.git#egg=elephant-0.1.1
```

and I ended up getting this when I ran `notebook_test.py`
```
tests/notebook_test.py:11: AssertionError
---------------------------------- Captured stdout call ----------------------------------
Not a valid NeuroML 2 doc: (<type 'exceptions.IOError'>, IOError(u'Error reading file \'../models/Cav1.channel.nml\': failed to load external entity "../models/Cav1.channel.nml"',), <traceback object at 0x1080b13f8>)
---------------------------------- Captured stderr call ----------------------------------
Traceback (most recent call last):
  File "IVCurve_Model.py", line 35, in <module>
    model = ChannelModel(channel_file_path,channel_index=0,name=channel_model_name)
  File "/Users/travis/.virtualenvs/test/src/neuronunit/neuronunit/models/channel.py", line 17, in __init__
    channels = ca.get_channels_from_channel_file(self.nml_file_path)
  File "/Users/travis/.virtualenvs/test/lib/python2.7/site-packages/pyneuroml/analysis/NML2ChannelAnalysis.py", line 246, in get_channels_from_channel_file
    channels = list(doc.ion_channel_hhs.__iter__()) + \
AttributeError: 'NoneType' object has no attribute 'ion_channel_hhs'
```

Not sure if this is to do with the incorrect version of `elephant` I apparently have (when I do the install command given above, it still installs `0.1.0`) or something internal to the script.

**Comment by rgerkin** [comment]
@travs 
I think the dependency links are working correctly at least on Travis-CI because it is installing the right versions there, but maybe there is something else going on when you try to install a different way.  

But the error you are getting is not elephant or neuronunit related.  It is what you get when the NeuroML doc doesn't load correctly, or when libNeuroML is the wrong version.  Let me reproduce everything on a clean Ubuntu VM and I'll get back to you with the recipe.

**Comment by travs** [comment]
@rgerkin Ok, thank you Rick :smile: 
The issue with dependency links won't show up directly in Neuronunit, but rather when installing neuronunit via `pip install git+https://...`. One way around this would be for CW to install neuronunit by cloning the git repo and installing locally with `python setup.py install`.

I can take care of the installation issues for sure, as long as I can get the notebook running in a local environment.

**Comment by rgerkin** [comment]
@travs 
I switched my setup.py script from distutils to setuptools recently, precisely so that the dependency links would be honored on setup.py install.  But maybe that keeps them from being honored in pip install?

**Comment by travs** [comment]
@rgerkin Ahh, that may be the issue for installation.

**Comment by rgerkin** [comment]
OK, I got everything working on a blank Ubuntu VM (the default Ubuntu selection in Amazon EC2).  [Here](https://gist.github.com/rgerkin/6e3cedc39c6ce3c212f8) is what was required.  

However, none of that really has anything to do with the source of the error.  It was actually several changes in ChannelWorm that were responsible, so I updated IVCurve_model.py in cbbc343 to account for those.  

First, the relative path to the NML file wasn't working, so I made the path determination more robust.  See the `IOError(u'Error reading file \'../models/Cav1.channel.nml\': failed to load external entity "../models/Cav1.channel.nml"',` section in your traceback above, which just says it couldn't find the file.  

Second, the Initiator class has a new location, and new method names.  

Third, the channel model name, and the path to the experimental data had changed.

**Comment by travs** [comment]
Ok, thanks for that Rick. :smile: 

We should probably have another discussion about keeping the [notebook](https://github.com/openworm/ChannelWorm/blob/aedbf9c3730d878df5a1c4964f3aa9a3331c87c1/tests/SCU_IVCurve_Model.ipynb) and [script](https://github.com/openworm/ChannelWorm/blob/aedbf9c3730d878df5a1c4964f3aa9a3331c87c1/tests/IVCurve_Model.py) in sync as well, since there are a few steps required right now (make changes in one, replicate in the other).

We discussed something over in #102 as well, but since the current errors involve changing the .py script itself, maybe we don't have to change anything in the notebook.

**Comment by rgerkin** [comment]
@travs I think the script should never be edited manually.  It should only be produced via `nbconvert` from the notebook.  In fact, this will also tell us if the notebook is likely to work from a vanilla installation.

**Comment by pgleeson** [comment]
@rgerkin @travs, the parameters used in [this script](https://github.com/openworm/muscle_model/blob/master/NeuroML2/ivcurve_ca_boyle.sh) should probably be used for generating the iv curve from the nml file. See also https://github.com/openworm/ChannelWorm/issues/96#issuecomment-134233138
