### ISSUE TITLE
Document how to plot multiple series on one plot

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#158]
It's not clear to me how to plot two or more series for a single plot, such as this [one](http://channelwormdjango-channelworm.rhcloud.com/media/ion_channel/graph/2015/08/09/Screen_Shot_2015-08-09_at_10.01.35_AM.png)

This was raised by @stripathy at the hackathon.

@VahidGh @miladjafary Any tips?

Also, we should document this for future use.

**Comment by travs** [comment]
Related to #98

**Comment by rgerkin** [comment]
@travs For context, what plotting environment are we talking about?  

Also, perhaps unrelated, but @VahidGh may need to separate multiple series plotted on the same graph using pyNeuroML, each corresponding to gating variables, and replot them on separate graphs to compare to gate plots for channelpedia.

**Comment by travs** [comment]
@rgerkin Good point. I'm talking about the digitization section of the channelworm web app. Namely, how to create separate datasets for one figure.

**Comment by VahidGh** [comment]
@travs, I'm referring to https://github.com/openworm/ChannelWorm/issues/46#issuecomment-127539388, as I described the process I did for 1-2 channels.

For more clarification -- We have an option called `Manage Datasets`, which is available when `Calibrate Axes` is done. With this option we can have separate digitized series for each trace. 
![image](https://cloud.githubusercontent.com/assets/6655104/9200471/33527b20-405d-11e5-8c60-766f208bfa10.png)

The other issue is with the holding potential for each trace. As described, this is available through the I/V, G/Gmax vs V, or any voltage-dependent curve within the same study. For example for the top trace, we should look for the I/V curve and using the captions, we can find out which holding potential is for this trace (e.g. 80 mV), and then renaming the dataset to 80 for the fitting process.

**Comment by travs** [comment]
@VahidGh Ok excellent. I wasn't aware of the manage datasets option; thanks for pointing that out.

I'll write up a bit more documentation for this as I go through digitizing some figures today.

Do you have any recommendations for where to place points on these figures with no included data points? How many/where to put them?

**Comment by VahidGh** [comment]
@travs, great. As for the points, should at least cover the whole trace, considering it has started from some baseline, then for example we have a curve that should be simulated via points, then some points for the steady state current, and then again where the clamped voltage stops (the vertical line (if there is), and then again the baseline. 

Other adjustments would be required during the fitting process.

**Comment by travs** [comment]
Ok, I guess I was thinking there was some number we could use, but I'll just go with whatever seems to cover the curve visually.
