### ISSUE TITLE
Units in loaded experimental data

### ISSUE THREAD

**Issue by rgerkin** [openworm/ChannelWorm#180]
Units are not always consistent in loaded experimental data.  For example, in #179 one way loads the data in mV and the other loads it in V.  Since `ion_channel.models.Graph` has a field for units, we should write a wrapper function around `ion_channel.Graph.objects.get` that automatically applies units using the python `quantities` module.  Then we won't have to check manually retrieve and apply the units each time we run a test.

**Comment by VahidGh** [comment]
The `quantities` package is cool. I was looking for something like this before. I found some built-in package in python (which I don't remember the name, right now!), that supports the main units and conversions like meter, grams, etc and needed to define customized units.
This package seems to be more flexible, thanks.

**Comment by rgerkin** [comment]
OK, I am going to push a quantities-friendly implementation of a GraphData method, and an updated version of the test notebook, later today.

**Comment by rgerkin** [comment]
Implemented in bb67f0e with the `asunitedarray` method of `GraphData`.
