### ISSUE TITLE
Store output of SciUnit tests in S3 bucket

### ISSUE THREAD

**Issue by gsarma** [openworm/ChannelWorm#185]
SciUnit tests convey more information than ordinary unit tests.  Ultimately, to have a standalone information dashboard for SciUnit, we would like to have the output of these tests stored in an S3 bucket.  

See also: 
1) https://github.com/joebowen/model_completion_dashboard 
2) http://docs.openworm.org/en/latest/Projects/muscle-neuron-integration/#model-completion-dashboard
3) #184 and #186

@rgerkin @slarson @cheelee

**Comment by rgerkin** [comment]
@gsarma @slarson @cheelee
I had originally envisioned using S3 for this, as Travis has very [simple deployment](https://docs.travis-ci.com/user/uploading-artifacts/) of artifacts to S3 buckets.  

However, S3 does cost money, and as cheap as it is (the bill will probably be in the ones of dollars total for the first few months) it will go up cumulatively as long as we are adding new testing artifacts.  As we test more things, more often, this could conceivably grow larger than any person feels comfortable paying.  

So I'd like to entertain a free option, like Google Drive.  Thoughts?

**Comment by gsarma** [comment]
That sounds reasonable to me, and of course, we can shift things to S3 in the future if it seems like the right thing.  As for now, will it be as straightforward as using S3?  

Also referencing #144 and #145 as we should also be storing timing information in order to catch performance regressions.

**Comment by rgerkin** [comment]
Using OpenWorm S3 credentials provided by email.

**Comment by gsarma** [comment]
What is the status of this?
