### ISSUE TITLE
Pull request in the command that exports ion channel data for PyOpenWorm

### ISSUE THREAD

**Issue by slarson** [openworm/ChannelWorm#189]

**Comment by slarson** [comment]
Update on this.  Let's not wait for the additional data; lets go ahead and put this online even if just in your own personal fork of PyOpenWorm

In order to get this running on my side I will re-run insert_worm.py in the forked version.

@shubhsingh594 just point me at the repo and branch that has this change when ready.

**Comment by gsarma** [comment]
@slarson I'm not sure I understand this issue- can you elaborate?
