### ISSUE TITLE
Estimate parameters for modeling ion channels with no patch clamp data available

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#25]
Using some machine learning algorithms we should estimate parameters such as Conductance, reverse potential, and the rate of activation/inactivation in order to build HH models for ion channels with no patch clamp data available. 
The steps would be as follow:
- [ ] Find data-sets and decide on the input types
- [ ] Decide on the structural properties of ion channels could be used for the feature selection
- [ ] Choose the right algorithm for this purpose
- [ ] Do the preprocessing step
- [ ] Do the training step
- [ ] Validate and improve results

**Comment by travs** [comment]
@vahidgh @a-palyanov

Hey guys, since our discussion last week, what do you think are some concrete next actions for moving this one forward? Perhaps we can raise them in sub-issues?

**Comment by VahidGh** [comment]
@travs, #112, #113, and #114 are starting points for this issue.

**Comment by travs** [comment]
@VahidGh Excellent! Please close #106 if it is redundant now; I'm not sure.

**Comment by VahidGh** [comment]
@travs, actually I separated #116 to three different issues.

**Comment by travs** [comment]
Ok, I'll update #106 to reflect this.
