### ISSUE TITLE
Develop validation test template

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#27]
The template will be used to make it easier for contributors to create tests.

Implementation will be similar to the drawing below:

![svovl47fu27mfnaddbdysng](https://cloud.githubusercontent.com/assets/7369273/7517933/7d752578-f4b2-11e4-8f0c-3335031a85e6.png)

These are the steps building the template will require (may be modified as we move forward):
- [x] Set up unit testing framework (SciUnit or NeuronUnit)
- [x] Set up model imports (i.e. Grab channel models)
- [ ] Set up two example data imports (one for data tables, one for patch clamp data)
- [x] Integrate with Travis CI

**Comment by travs** [comment]
In progress with the development of [an example](https://github.com/VahidGh/ChannelWorm/blob/b8e3b3c8a684b27565b41403e071e6a7e2d9a553/tests/IVCurve_Model.ipynb)

**Comment by rgerkin** [comment]
I'll refactor NML2ChannelAnalysis a bit so I can use its components for a SciUnit-based version of the example.

**Comment by travs** [comment]
@rgerkin sounds great! :smile:

**Comment by travs** [comment]
Status report:

- There is a validation test template for ion channel models with patch clamp data as a result of work by @rgerkin (iPy notebook in the `tests` directory).

- There is not yet a validation test template for ion channel models *without* patch clamp data available.

**Comment by travs** [comment]
We will backlog this issue while we wait for #25

**Comment by travs** [comment]
Going to close this one since it's really two separate issues (validation test templates for ion channel models (1) with and (2) without patch clamp data), and link to this issue from the related issues that I will raise.
