### ISSUE TITLE
Expand list of figures to include 7 I/V curves and 7 I/t plots

### ISSUE THREAD

**Issue by slarson** [openworm/ChannelWorm#39]
We [have a spreadsheet](https://docs.google.com/spreadsheets/d/1jTXDHsLsdK-T_d-RwCb4gmQgMhjumvZE7C_2PEXFYAk/edit#gid=0) that we need to populate with figures that need to be digitized.  There is a folder of [ion channel papers](https://drive.google.com/folderview?id=0B4qffTA1q81rfmhoZzBva2xKRTJIVTlhR2plYTF2S2JCNXBLODJWN09KUHU4X09FN0hEQlE&usp=sharing).  We should go paper by paper and add figures into the spreadsheet from here.

**Comment by slarson** [comment]
@travs @VahidGh let's get a session scheduled to do this in the next week or so.

**Comment by travs** [comment]
Discussion for this session is over on Gitter, [starting here](https://gitter.im/VahidGh/ChannelWorm?at=5568b1b2777c17d06a133f42)

**Comment by travs** [comment]
@stripathy @vahidgh

Along with #71 and #8, this depends on the authentication (#103) being in working order, so we can insert into the database and nail down a workflow/walkthrough for going from a plot in a paper to an ion channel model ready for export to PyOpenWorm.

**Comment by travs** [comment]
@stripathy @vahidgh

Along with #71 and #8, this depends on the authentication (#103) being in working order, so we can insert into the database and nail down a workflow/walkthrough for going from a plot in a paper to an ion channel model ready for export to PyOpenWorm.

**Comment by travs** [comment]
Next steps are to populate the plot type column in [the spreadsheet](https://docs.google.com/spreadsheets/d/1jTXDHsLsdK-T_d-RwCb4gmQgMhjumvZE7C_2PEXFYAk/edit#gid=0). If we have >7 of each type, we can close this issue, and create checklists in #73 and #71 for collecting, and #72 for digitization.

**Comment by slarson** [comment]
@travs is this done now?

**Comment by travs** [comment]
@slarson Just finished reviewing the plots we've selected in [the spreadsheet](https://docs.google.com/spreadsheets/d/1jTXDHsLsdK-T_d-RwCb4gmQgMhjumvZE7C_2PEXFYAk/edit#gid=0) and coded them by plot type.

We have 16 I/V plots and 19 I/t plots selected, plus various other plots.

Well on our way :+1:
