### ISSUE TITLE
Using standards for current and voltage waveforms, and analysis

### ISSUE THREAD

**Issue by rgerkin** [openworm/ChannelWorm#40]
Are we going to use standards like [NEO](https://github.com/NeuralEnsemble/python-neo) to represent and process our waveforms, or just use arrays or tuple of arrays to represent them?  

Are we going to use emerging standards like [ElePhanT](https://github.com/NeuralEnsemble/elephant) to do the actual calculations (e.g. compute the mean of or counts spikes in a segment of membrane potential), or roll our own?

**Comment by slarson** [comment]
As for ElePhanT -- I see this working with spike train type data which is great but fundamentally we need to work with analog signals, not spike trains.  

NEO does seem to have an [analog signals data structure](https://pythonhosted.org/neo/core.html#data-objects).  We should try to reuse this.

**Comment by rgerkin** [comment]
ElePhanT has a lot of spike train stuff but is intended to be useful for analog data as well.  It is also NEO based, so the methods will work on NEO objects.  For example, you take an analog signal and filter it in some way, or count threshold crossings, or compute a resistance and capacitance from a voltage step, etc.

**Comment by pgleeson** [comment]
Currently, [neurotune](https://github.com/pgleeson/neurotune) uses a package, [pyelectro](https://github.com/pgleeson/pyelectro) developed by @vellamike for these types of analyses (I've forked these for working with NeuroML/c302). See https://github.com/pgleeson/pyelectro/blob/master/pyelectro/analysis.py#L368 for example.

A lot of these methods could be (as was @vellamike's intention) replaced with methods in Elephant. A gradual process of migrating methods from pyelectro to Elephant (using NEO where appropriate) might be best, as both those packages are updated and used for ChannelWorm, c302 etc.

**Comment by VahidGh** [comment]
@rgerkin, Thank you for these helpful information.
@pgleeson, Ok, going to dig into these codes. Thanks for discussions and helpful guides you also provided the other day.

**Comment by VahidGh** [comment]
@rgerkin, I couldn't find any [implemented function](http://elephant.readthedocs.org/en/latest/modules.html) for voltage-/current- clamp analysis in the Elephant package.
Do you know any other known package (especially for voltage-clamp analysis) in Python?

**Comment by rgerkin** [comment]
@validgh Maybe [stimfit](https://github.com/neurodroid/stimfit), but I think that is more for single synaptic events.  I-V curves are so simple by comparison that there may be no formal package for dealing with them.

**Comment by travs** [comment]
#61 and #44 will be using points made in this discussion.
We'll close this for now and bring the implementation discussion over there.

**Comment by rgerkin** [comment]
I'm just going to throw this out there:  
https://github.com/BlueBrain/eFEL
While small now, it's a pretty huge deal because in principle due to the size of the related project.  Also @stripathy did AIBS release something like this as well, or is just whatever you've made to interact with their data?

**Comment by stripathy** [comment]
@rgerkin - no, as far as I know, AIBS has yet to release their code for calculating ephys features given an input set of sweeps (or model optimization?), but when I asked them they said it was on their "to-do" list but made no promises about when it would be made available.

I want to play with the eFEL stuff - can we make getting it running on one of the AIBS ephys data sets an action item?

**Comment by VahidGh** [comment]
@rgerkin, coo! It seems like the eFEL project is also a new project (began from this May), but how is this different from previous projects of the BBP?!

**Comment by rgerkin** [comment]
@VahidGh I think it's the first time they released anything of this sort, i.e. public tools.

**Comment by travs** [comment]
Any additional thoughts on what the next action(s) should be on this one?

**Comment by rgerkin** [comment]
@travs Maybe: all tests should be written using NEO objects when possible, and using Elephant analysis methods when possible.  So, for example, instead of just handling a unitless numpy array of value for the membrane potential or the current, we use (in the test notebooks) NEO AnalogSignal objects, which have units, durations, start times, etc.  I will work on this next time I edit one of the test notebooks.
