### ISSUE TITLE
Develop method to insert plots into PyOpenWorm

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#44]
With the [Experiment data model](https://github.com/openworm/PyOpenWorm/blob/channelworm/PyOpenWorm/experiment.py) we are able to store conditions in the database.

This can be expanded to include inserting digitized plots, but methods need to be created in the existing class (linked above) to allow inserting and retrieving of columns of data.

**Comment by VahidGh** [comment]
@travs, Good one.
@miladjafary, We can also use this data model or expand this for storing/retrieving data related to patch-clamp experiments.
Using this data model, we can also omit saving digitized data as csv files, right?
@miladjafary, what do you think? Is it OK to save data from the digitizer in DB instead of csv files?

**Comment by miladjafary** [comment]
@VahidGh I agree with saving in DB but i think it's better save it in CSV format as a field value. what do you think ?

**Comment by VahidGh** [comment]
I think it's a good idea to store all data in one place, storing in files reduces mobility.
We can consider this as a TODO, and working with csv files for now.

**Comment by miladjafary** [comment]
You mean every row of csv files convert to a Record in DB? If yes, aging I suggest csv content save as a text field in DB. also i thought that we want save digitizing data in DB.

**Comment by travs** [comment]
@miladjafary @VahidGh Do we still think we should do this? And how should we store these plots, now that the backends for CW and PyOW are distinct?

**Comment by VahidGh** [comment]
Now we are keeping each plot/graph in DB, and could be retrieved as array (take a look at [this](https://github.com/openworm/ChannelWorm/blob/master/channelworm/ion_channel/models.py#L215), But I'm not sure if we need to keep them in PyOW DB!

**Comment by travs** [comment]
@VahidGh Ok that function looks awesome!

Maybe the export function (#92) can push this data out as well? I will be working on that function today, so if you're around on gitter we can have a chat about it!

**Comment by VahidGh** [comment]
Sounds good, but still I'm not sure if PyOW aims to keep such data!

**Comment by travs** [comment]
@VahidGh 
Ok, the Export function is now complete, except for plot data. I can understand the concern about not wanting to replicate too much data in PyOpenWorm, and I agree that we should only pull the necessary data from CW.

If we're ultimately going to use PyOW as the backend to the model completion dashboard, however, we will need some way to show plots on the webpage. We *could* do this by doing GET requests on the CW web app, but that may make the two apps too interdependent. There may be another solution other than putting the plot CSVs in the PyOW db, and I am open to suggestions if this does not make sense to you.

**Comment by VahidGh** [comment]
@travs, I think it's not going to take much place in a DB, as it is right now.
Maybe we can keep it just in the ChannelWorm branch, and push it to the master, when we need to.
