### ISSUE TITLE
Difficulties in digitization of figures with no usual axes

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#46]
Some figures like this:

![egl-19-vclamp](https://cloud.githubusercontent.com/assets/6655104/7922008/b338896e-08be-11e5-8c04-c9d39a5394c8.png)

Having unclear axes. There are three issues regarding this problem:
1) Webplotdigitizer has no capability to calibrate axes in this way (with both x and y)
2) It's not clear what is the range of values (e.g. current in this picture) 
3) It's not clear what is the clamped voltage for each trace in a figure like this

What can we do when digitizing these kind of figures, to evaluate candidate models in the fitting/optimization process?

**Comment by slarson** [comment]
These figures follow a convention in neuroscience that is admittedly opaque, but in fact the information you are looking from is contained within the diagram.

The key insight is that the lengths of the lines in the legend in the upper right are equivalent to the value marked next to them, and they are in scale with the diagram.  

For example, the X-Axis starts at 0, and then if you take the distance of the horizontal bar in the legend and add it to the X-Axis, that is 50 ms.  So you can essentially "reconstruct" the X-axis in 50 ms intervals by taking that same length over and over.

Its the same for the Y-Axis, the vertical length is equivalent to 250 pA.  

In terms of what is the clamped voltage, and where is zero in the Y-Axis, you may need to consult either the caption of the figure, or in the worst case the methods section.

But I think with that much you should be able to use the Webplotdigitizer....

**Comment by VahidGh** [comment]
@slarson, Yep, I was doing the same thing by hand (and a ruler :) ) as there is no capability for this in Webplotdigitizer, but I think it is possible to add some feature to determine such axes.

@miladjafary , There is some similar capability for scaling maps in the WPD, but for one axis, maybe we can customize this one for both axes.

**Comment by travs** [comment]
@vahidgh What is the status of this one?

**Comment by VahidGh** [comment]
We've discussed with @miladjafary about this. It's a bit difficult to implement, but finally we need this feature or something like this. It's still an open issue...

**Comment by VahidGh** [comment]
OK, I found an easier way to deal with this issue:

1) As for calibrating axes, instead of using a ruler, or editing the original image, etc we can just put the mouse pointer on the end of the horizontal/vertical bar, keep the pixel coordinate (under the zooming panel) in mind, and subtracting this from the value of the beginning of the bar. Then choosing the first point of the axis in the plot, and adding the value to it's pixel coordinate, we can choose the second point of the axis.

2) If the I/V curve is available, then we should consider the first point of the Y axis, the same as the current for clamped voltage in the I/V curve. E.g. if the initial holding potential is -70 mV, then we should find the corresponding current value in the I/V curve (e.g. -0.8 pA). Then considering this, as the first value of the Y axis. 

3) In addition to the baseline, we need to find at least the clamped voltage for max and min currents in the I/V curve (or any similar curve such as normalized current, G/Gmax, ...). Then digitizing the min, max and baseline currents, and saving those datasets, under the name of clamped voltage (e.g. renaming the max current dataset as 50).

4) Another consideration is choosing the precise values for some critical points, e.g. we should simulate the curve in a trace with as much as points needed, choosing accurate points for the start and stop points (and also on/off points). WPD has a capability to adjust points by keyboard after choosing the point by mouse.
