### ISSUE TITLE
Decide on preferred outputs of the final channel model

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#51]
Assuming we have successfully fitted, optimized and validated parameters for each ion channel model, what are the preferred outputs for each model to be stored and shown via the interface?

These are the options came to my mind:
* Keeping parameters along with related score of the fitting process or validation test in a DB and generating the NeuroML2 file via some API, by request.
* Depicting figures of the voltage-dependent dynamics for each channel (including the steady states of activation/inactivation and the associated time constants)
* Each figure taken from publications in comparison with the simulated one

**Comment by travs** [comment]
@VahidGh 
I think all of those options have inherent values.
With respect to modularity, the first option seems most attractive. If CW was able to be used as a library or source of NML2 files we could easily embed them in muscle_model or c302.

**Comment by VahidGh** [comment]
@travs, agreed. Going to complete the Modelator class of the cwFitter.
As discussed with @miladjafary, the next step for the web app, would be showing these results for each ion channel.

**Comment by pgleeson** [comment]
I agree that an output in "pure" NeuroML 2 (along with plenty of metadata from the fitting in `<annotation>` elements) would be very useful.

**Comment by VahidGh** [comment]
@pgleeson, Of course. And also some graphs for better depicting the whole things.

**Comment by travs** [comment]
@vahidgh Is this one complete now?

**Comment by travs** [comment]
@vahidgh Hey, when we meet again this week can we talk about this one?

**Comment by VahidGh** [comment]
@travs, Of course, although we would need more help on the implementation
side.

**Comment by VahidGh** [comment]
Done. now it is possible to keep both parameters and NeuroML files. 
In order to get parameter storage done, we need to finish #63.
