### ISSUE TITLE
Find a permanent cloud deployment service for the web app

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#59]
Ideally we want as little downtime as possible.

Currently, we will deploy to OpenShift, but their basic plan has a "sleeping" period that takes a few seconds to wake from, so it will be less convenient when we want to send requests to this server if we go with that.

@joebowen mentioned [resource grants](https://www.openshift.com/resource-grants) that openshift offers, and that would be an awesome way to get a better service from them.

There may be other PaaS that provide similar services to OpenShift but with less/no downtime.
I'm not sure of the capabilities of any of these, but they may be worth checking into:
- PythonAnywhere
- Google App Engine
- Heroku

**Comment by slarson** [comment]
We've got an example running [here](http://channelwormdjango-channelworm.rhcloud.com/).  What more do we need to do to determine if this is "suitable"?

**Comment by travs** [comment]
I guess OpenShift is suitable, though I'm getting a 500 error from that link at the moment, and the sleeping period I mentioned is a negative if we want to pull data from it to other programs. 

Those are separate issues though, so we can close or rename this one.
