### ISSUE TITLE
Integrate UI with cwFitter

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#63]
In order to process user-provided data and fit to the model using _cwFitter_, we need to work with its _Initiator_ class. 
This class and related functions should be called from some _view_ pages of the Django web app. After choosing the channel type, providing patch-clamp data and digitizing graph(s), one should be able to start the fitting process and generating models.

**Comment by travs** [comment]
@VahidGh 
Hey Vahid, how is this issue coming along?

**Comment by VahidGh** [comment]
@travs, today, @miladjafary and I had a chat about these 2 issues. I did some changes to models, and I hope we would apply them to the UI by the end of this week.

**Comment by travs** [comment]
@vahidgh Awesome!

**Comment by travs** [comment]
@vahidgh @miladjafary
This one is complete now right?

**Comment by travs** [comment]
@VahidGh @miladjafary Hey, can we talk about this one in our meeting this week?
