### ISSUE TITLE
Use the algorithm's outputs to change the model's parameters

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#67]
To close this one we need to:
- [ ] Complete the TODOs stubbed out in the `initiators` class
- [ ] Get parameters to be fitted from the database and user interface

@VahidGh @miladjafary @slarson

**Comment by slarson** [comment]
@mcurtis125 check this out.  @travs can you help flesh out the description of this so that @mcurtis125 can get a sense of next steps?

**Comment by travs** [comment]
Just to close this loop temporarily, it appears that @VahidGh has been chatting with @mcurtis125 about this one and #68

**Comment by VahidGh** [comment]
@travs, @miladjafary tells me is working on this issue, which is also related to the integration of cwFitter with UI. 
And @MichaelCurrie tells he is also interested in working on some ML. We will probably go to start do some work related to [this milestone](https://github.com/openworm/ChannelWorm/milestones/Modeling%20ion%20channels%20with%20no%20patch%20clamp%20data), this week.

**Comment by travs** [comment]
Ok excellent.
@miladjafary: can you tell us the status of this one? 
Is there anything I can do to help?
