### ISSUE TITLE
Validate an optimized ion channel model

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#68]

**Comment by slarson** [comment]
@mcurtis125 check this out.  @travs can you help flesh out the description of this so that @mcurtis125 can get a sense of next steps?

**Comment by travs** [comment]
@VahidGh:
Have we done this already? I want to catch up on the optimization progress at the hackathon or earlier.
If there's anything you can point to in terms of completion for this issue let me know!

**Comment by VahidGh** [comment]
I think #96, and #138 are pre-requisites for resolving this issue.
