### ISSUE TITLE
Collect 7 I/V curves from journal articles

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#71]
Depends on #39

Listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1jTXDHsLsdK-T_d-RwCb4gmQgMhjumvZE7C_2PEXFYAk/edit#gid=0), which takes from [this folder](https://drive.google.com/folderview?id=0B4qffTA1q81rfmhoZzBva2xKRTJIVTlhR2plYTF2S2JCNXBLODJWN09KUHU4X09FN0hEQlE&usp=sharing)

**Comment by slarson** [comment]
@travs do we think this is done now?

**Comment by travs** [comment]
@slarson Since cutting these figures out of the papers is implicit in the digitization process, I think we can actually close this and take the discussion over to #72 .
