### ISSUE TITLE
Digitize the 7 I/V curves

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#72]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7

See: #71

**Comment by slarson** [comment]
@travs do we think this is done now?

**Comment by travs** [comment]
@slarson 4 out of 7 I/V curves are now digitized.
Check out 1,2,3, and 5 [over here](http://channelwormdjango-channelworm.rhcloud.com/ion_channel/graph/).

**Comment by travs** [comment]
Just did two more plots on 11 [here](http://channelwormdjango-channelworm.rhcloud.com/ion_channel/graph/), so this one's done now.
