### ISSUE TITLE
Show the final results through web app

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#75]
#51, is a relevant issue to this. We need to show these outputs to the user.

**Comment by travs** [comment]
Hey @miladjafary; what's the status of this one? I ran through a workflow and things look good! Is it safe to close this?

**Comment by miladjafary** [comment]
@travs actualy we are working on it with Vahid :d

**Comment by travs** [comment]
@miladjafary @vahidgh What is the criteria for closing this issue?
