### ISSUE TITLE
Show available info and models for each ion channel through web app

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#76]
A page is needed to show available info and models for each ion channel.
Related to #7 and #75.

**Comment by slarson** [comment]
I think it makes sense to start building the bottom-most part of [this
interface](
http://docs.openworm.org/en/latest/Projects/model-completion-dashboard/) in
relation to this :)
ᐧ

**Comment by miladjafary** [comment]
@VahidGh I think that we have all related information  which is came to @slarson interface, "Ion Channel Parameter".

**Comment by VahidGh** [comment]
@miladjafary, Yep, but we need also to add those figures.

**Comment by mwatts15** [comment]
Broken link in https://github.com/openworm/ChannelWorm/issues/76#issuecomment-112196136. Think it should be http://docs.openworm.org/en/latest/Projects/muscle-neuron-integration/#model-completion-dashboard now.
