### ISSUE TITLE
Design a home page for the web app

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#77]
We need to design and implement a home page that covers at least:
- Overall info about the ChannelWorm + OpenWorm
- A brief tutorial about how the modeling pipeline works
- Some navigation tools for accessing each ion channel

**Comment by slarson** [comment]
Good point.  I would encourage that the home page be a simple landing page though and that it points out to http://channelworm.readthedocs.org for the substantive content (tutorials, in depth info, etc)

**Comment by miladjafary** [comment]
I am trying to design an sketch of Home page and share it here , so we can talk about it here more

**Comment by VahidGh** [comment]
@miladjafary, Great!
