### ISSUE TITLE
Collect data for voltage-dependent ion channels

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#8]
Collect data for these voltage-gated/calcium-activated ion channels with priority of expression in muscle cells and motor neurons:
- Voltage-gated calcium channels (VGCC): EGL-19 (Cav1: L-type), UNC-2 (Cav2: R, N, P/Q-Type), and CCA-1 (Cav3: T-Type)
- Voltage-gated potassium channels: SHK-1 (Shaker, Kv1), EXP-2 (Shab, Kv2), EGL-36 (Shaw, Kv3) and SHL-1 (Shal, Kv4)
- Calcium-activated Slo-like potassium channels: SLO-1, SLO-2

For Kv1, Kv4, and Cav1, data and related models are available, we just need to insert the parameters into the PyOW.

**Comment by slarson** [comment]
We need to set up a dropbox folder with PDFs for these channels and have a google sheet that links to each one.  PDFs need to definitely have I/V curves for digitizing purposes.

**Comment by VahidGh** [comment]
I set up [this folder](https://drive.google.com/folderview?id=0B4qffTA1q81rfmhoZzBva2xKRTJIVTlhR2plYTF2S2JCNXBLODJWN09KUHU4X09FN0hEQlE&usp=sharing) with related references. Some of them do not have I/V curves, but would be useful for citing purposes.

**Comment by VahidGh** [comment]
I've almost finished the first version of the fitter. Now I need some reliable data from digitized IClamp, VClamp, and I/V curves to start testing my code. 
Any kind of help would be appreciated.

**Comment by travs** [comment]
The channels we're looking at are listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1jTXDHsLsdK-T_d-RwCb4gmQgMhjumvZE7C_2PEXFYAk/edit#gid=0), which takes from [this folder](https://drive.google.com/folderview?id=0B4qffTA1q81rfmhoZzBva2xKRTJIVTlhR2plYTF2S2JCNXBLODJWN09KUHU4X09FN0hEQlE&usp=sharing)

**Comment by stripathy** [comment]
A few questions I had while going through ~5 papers for channels data:

1. What's the data we're looking for? Data from cultured c-elegans neurons? From cells in which a single channel had been expressed (like a xenopus oocyte cell)? What's the right way of encoding either of these?
2. What are the different current quantification types (I/V V/I G/Gmax, etc)? Which are useful? How do you encode these?

**Comment by VahidGh** [comment]
@stripathy, thanks for your comment. 
As for the cell type, we are going to store data related to any kind of experiment. As we might generate different models for a single channel, and decide on the best one during a higher level optimizations ([C302 projec](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302)).

Some effects based on different experimental conditions (such as the cell type, age, temperature, etc) are going to be saved for further analysis (some of them are not still included in the current data model, but will be very soon).

And regarding the different types of figure you mentioned, the approach is to simulate the original voltage- or current- clamp (or even both), that the experiment is based on, and then generate each of the plots that are available in the literature to compare with the simulated one (also for the evaluation purposes during the optimization phase). But currently the priority is with I/V curve, which is more common.

**Comment by stripathy** [comment]
Regarding the issue of what IV curves are useful for the modeling team (e.g., is representing current as "normalized current" OK, is representing current as picoAmps better, etc), we should ask what needs to be extracted so that the IV curve can be represented in neuroML.

**Comment by VahidGh** [comment]
@stripathy, Actually I've considered a parameter named `toSI` for these kind of conversions, but the 'normalized current' that we saw in that paper was so rare, the first time I've ever seen in an article! Will consider an special case for this one. 
But in general, we consider SI units for the final result (with some pico, mili, etc for simpler showing) and what is considered in the original paper for comparison and evaluation purposes.

**Comment by travs** [comment]
This is broken down into #71 #72 and #39.

We can close this when those are closed, and any further discussion can be redirected to one of those issues.

**Comment by travs** [comment]
Just closed the remaining issues on this one, so as mentioned in the previous comment, I'm closing it now.

**Comment by VahidGh** [comment]
@travs, I think it is done when the above-mentioned channels and related papers are digitized and available through the app for further fittings/modeling.

**Comment by travs** [comment]
@VahidGh Sure, we'll leave it open then. May help to have a checklist so we can see how far we are with this, and can know when to close it.
