### ISSUE TITLE
Move SciUnit models/tests/capabilties to their own branch/repo/directory

### ISSUE THREAD

**Issue by rgerkin** [openworm/ChannelWorm#97]
I propose taking the notebook [here](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb), and moving all the models, tests, and capabilities declared in those cells into their own repo.  

The capabilities and tests are generic enough to be in NeuronUnit.  The models (just one for now) could be in a ChannelWorm branch called scidash or just a scidash directory.  The name scidash comes from a web framework I am working on for visualizing scoring in large numbers of model/test combinations.  I have a skeleton repo [here](http://github.com/scidash/scidash) that describes the target structure.  We will be able to use this for a dashboard that goes beyond generic Travis-CI output.  

The capabilities and tests in the scidash directory would just import from NeuronUnit (to which I will move the corresponding entities that I defined [here](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb)), and the models would be the channels, for example the ones tested in the same location.  The IPython notebook would then be reduced to outer-loop stuff, i.e. specifying the channels to be tested, simulation metadata, and sources of experimental data to parameterize tests.

**Comment by travs** [comment]
@rgerkin 
It would be nice to have some of this stuff abstracted away into another library/repo as you suggest, and incorporate it the same way we incorporate SciUnit right now.

If we were able to simply define the tests we wanted and the models we wanted to test via a notebook or single test script in ChannelWorm, it would simplify the repo's contents a bit.

I think we should wait until the loop is closed on [this milestone](https://github.com/VahidGh/ChannelWorm/milestones/Develop%20validation%20tests%20for%20simulated%20and%20digitized%20channel%20data) before deciding on whether to make a move though, and make sure everything is able to run locally as well as on TravisCI. Given the great work you have done lately this should be quite soon.

What do you think think @VahidGh ?

**Comment by VahidGh** [comment]
@rgerkin, @travs, Sounds good, and would be very useful if we can integrate the SciUnit tests and OSB model validations on Travis CI.

**Comment by rgerkin** [comment]
@VahidGh @travs Until we have a better grasp on acceptable score ranges, scaling errors in the simulation, etc., let's just have Travis-CI run the sciunit tests and get a score, but not actually assert that the test passed.  Getting through the testing and producing a score should be sufficient for now.
