### ISSUE TITLE
Add digitization best practices to the walkthrough

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#98]
Plots like those digitized by @rayner in openworm/muscle_model#40 do not have original data points, nor zeroed axes. 
The current walkthrough does not address this possibility, so the practices employed by @rayner should be included there as well.

**Comment by VahidGh** [comment]
@travs, for Vclamp data (V/t), the best (and easiest) approach I could find to fit data is to have at least data for top, bottom, and the trace along with the base voltage.
The stimulation voltage for these traces are usually available via the I/V curve. e.g. the top and the bottom traces are those with maximum and minimum current values in the I/V curve, and the voltage value for the trace along with the base voltage can be find in the text/caption.
So for digitizing a V/t curve, we can create 3 datasets within the same digitized graph and then name each dataset with the value. e.g. the name of the top one is 80, the bottom one, -10, and the baseline, -70. Then we can use these names as values during the fitting process.

**Comment by VahidGh** [comment]
#46 is relevant to this.
